x-phoenix: &phoenix
  build:
    context: .
    dockerfile: Dockerfile
  links:
    - db-elixir_template
  volumes:
    - ../:/app:delegated
    # For Windows and Mac compatibility with Fly CLI
    - type: bind
      source: ${USERPROFILE:-$HOME}/.fly
      target: /root/.fly
      consistency: delegated
    # Git configuration
    - type: bind
      source: ${USERPROFILE:-$HOME}/.gitconfig
      target: /root/.gitconfig
      consistency: delegated
    - type: bind
      source: ${USERPROFILE:-$HOME}/.ssh
      target: /root/.ssh
      consistency: delegated
  env_file:
    - path: .env
      required: false

  ports:
    - 4000:4000

  environment:
    - MIX_ENV=dev
    - NODE_ENV=dev
    - DATABASE_URL=postgres://postgres:postgres-elixir_template@postgres-elixir_template/elixir_template
    - PHX_HOST=localhost

services:
  db-elixir_template:
    container_name: postgres-elixir_template
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres-elixir_template
      POSTGRES_DB: postgres-elixir_template
      POSTGRES_USER: postgres
    healthcheck:
      test: pg_isready -U postgres -h localhost
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - db-data-elixir_template:/var/lib/postgresql/data

  devcontainer-elixir_template:
    <<: *phoenix
    container_name: devcontainer-elixir_template
    command: sleep infinity

  # app-elixir_template:
  #   <<: *phoenix
  #   command: mix do deps.get, deps.compile, compile, ash.setup, ash.migrate, phx.server
  #   ports:
  #     - "4000:4000"
  #   healthcheck: #TODO: benchmark compile time on local and ec2 machines
  #     test: curl --fail http://localhost:4000 || exit 1
  #     interval: 60s
  #     retries: 5
  #     start_period: 30s
  #     timeout: 10s
  #   depends_on:
  #     db-elixir_template:
  #       condition: service_healthy

volumes:
  app:
  db-data-elixir_template:
