defmodule ElixirTemplate.Repo.Migrations.AddThemePreference do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      modify :username, :citext, null: true
      add :theme_preference, :text, default: "system"
    end
  end

  def down do
    alter table(:users) do
      remove :theme_preference
      modify :username, :citext, null: false
    end
  end
end
